AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'vendor/**/*'

Gemspec/OrderedDependencies:
  Enabled: false # I like to group them, so what?

Metrics/BlockLength:
  Max: 30
  Exclude: # Grape's DSL rather expects large blocks
    - app/api/location_service/**/*

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 180

Metrics/AbcSize:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 12

Metrics/CyclomaticComplexity:
  Max: 12

Layout/LineLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/HashAlignment:
  # I like to space repeated grammars out tabulated, defund these cops
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineOperationIndentation: # works very poorly
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

