language: ruby
before_install:
  - gem install bundler
install: bundle install --jobs=1 --retry=1
script:
  - bundle install
  - bundle exec rspec

rvm:
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-9.0.4.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  matrix:
    - RAILS=3.2.22
    - RAILS=4.1.13
    - RAILS=4.2.5.1
    - RAILS=master
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"

notifications:
  email: 
    recipients:
    - buermann@gmail.com
    on_success: change
    on_failure: always
