language: ruby
before_install:
  - gem install bundler -v 1.17.3
install: bundle install --jobs=1 --retry=1
script:
  - bundle install
  - bundle exec rspec

rvm:
  - 2.3.1
  - 2.4.0
  - 2.5.0
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

env:
  global:
    - JRUBY_OPTS="-J-Xmx1024m --debug"

notifications:
  email:
    recipients:
    - buermann@gmail.com
    on_success: change
    on_failure: always
